spring.application.name=auth-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
logging.level.root=${LOG_LEVEL:INFO}
server.port=${SERVER_PORT:8080}

# ===============
# Redis config properties
# ===============
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}

# ===============
# Jwt config properties
# ===============
auth.secret.privateKey=${AUTH_SECRET_PRIVATE_KEY}
auth.secret.publicKey=${AUTH_SECRET_PUBLIC_KEY}
auth.token.validity=${AUTH_VALIDITY_SEC:3600}
auth.unique.key.id=${AUTH_UNIQUE_KEY_ID}

baseUrl.user-service=${USER_SERVICE_BASE_URI}
