spring.application.name=analytics-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
logging.level.root=${LOG_LEVEL:INFO}
server.port=${SERVER_PORT:8080}

# ===============
# MySQL config properties
# ===============
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============
# Kafka config properties
# ===============
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}

baseUrl.user-service=${USER_SERVICE_BASE_URI}