spring.application.name=url-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
logging.level.root=${LOG_LEVEL:INFO}
server.port=${SERVER_PORT:8080}

app.machine-id=${MACHINE_ID}

# ===============
# MySQL config properties
# ===============
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


baseUrl.user-service=${USER_SERVICE_BASE_URI}
app.base-url=${REDIRECTION_DOMAIN_NAME}